### ISSUE TITLE
[Bug]  **world size is 4** but have 0 available devices

### ISSUE THREAD

**Issue by flckv** [facebookresearch/hydra#2666]
# 🐛  world size is 4 but have 0 available devices 
## Description
srun` fairseq-hydra-train`  command to continue pretraining of wav2vec on librispeech following the steps [here](https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#train-a-wav2vec-20-base-model) is NOT recognising the gpus specified in bash script

## To reproduce

I set parameters in /home/flck/fairseq/examples/wav2vec/config/pretraining/`wav2vec2_base_librispeech.yaml`

distributed_training:
  `distributed_world_size`: **4** 
  ddp_backend: legacy_ddp

optimization:
`  update_freq:` **[16]**

in the shell script I specified the resources -- importantly **--gres=gpu:4**  : see below:

#SBATCH --job-name=ol            # Job name
#SBATCH --output=/home/flck/output_.%A.txt   # Standard output and error log
#SBATCH --nodes=2                   # Run all processes on a single node   
#SBATCH --ntasks=4                  # Run on a single CPU
#SBATCH --mem=128G                   # Total RAM to be used  
#SBATCH --cpus-per-task=8          # Number of CPU cores
#SBATCH --gres=gpu:4                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

I used the command with the parameters: 

srun fairseq-hydra-train  --config-dir /home/flck/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech 

( instead of adding the arguments: distributed_training.distributed_world_size=4 +optimization.update_freq='[16]' of the  fairseq-hydra-train I added them in the yaml file mentioned above. )

but I got error:

#### AssertionError: **world size is 4** but have 0 available devices

Why the above-specified 4 GPU is not recognized?

## Expected Behavior

specify the 4 gpus to continue pre-training on multi node multi gpu

## System information
- **Fairseq Version** : 0.12.2
- **Hydra Version** :  Hydra 1.0.7 omegaconf-2.0.6
- **Python version** : 3.9.7
- **Virtual environment type and version** : = conda 4.11.0
- **Operating system** : Linux-5.4.204-ql-generic-12.0-19-x86_64-with-glibc2.31

**Comment by flckv** [comment]
the solution was to add the params:distributed_training.distributed_world_size=4 +optimization.update_freq='[16]' in the config file instead
